### PR TITLE
Vitaly sponsors

### PR DESCRIPTION
**Pull request by Vitalidov**

### CODE REVIEW

**Comment by tghosth** [comment]
@Vitalidov does this need merging? Can you revert the CNAME change?

**Comment by Vitalidov** [comment]
I didn't change CNAME ????

**Comment by tghosth** [comment]
Erm
Screenshot_20201014-210458__01

**Comment by Vitalidov** [comment]
weird... so, if CNAME changes - the github-pages should not work... but it
works ....

I don't know....

**Comment by tghosth** [comment]
If this needs merging, please can you revert the CNAME change?

**Comment by Vitalidov** [comment]
No need merge ...

**Pull request closed without merging**
